<?php
// lang.php - ملف اللغات
$lang = [];

if ($_SESSION['lang'] == 'ar') {
    // العربية
    $lang = [
        'site_title' => 'مرفق',
        'welcome_title' => 'مرحباً في نظام إدارة النظافة',
        'welcome_desc' => 'نظام متكامل لإدارة وتتبع أعمال النظافة في المناطق والمباني',
        'login' => 'تسجيل الدخول',
        'learn_more' => 'المزيد',
        'features' => 'مميزات النظام',
        'role_admin' => 'المالك',
        'role_admin_desc' => 'الإشراف العام وإنشاء الحسابات وعرض التقارير',
        'role_supervisor' => 'المشرف',
        'role_supervisor_desc' => 'تحديد مواقع العمال وتعيين المهام',
        'role_worker' => 'عمال النظافة',
        'role_worker_desc' => 'استقبال المهام وتسجيل الإنجاز',
        'footer_desc' => 'نظام إدارة النظافة المتكامل',
        'all_rights' => 'جميع الحقوق محفوظة',
        
        // صفحة تسجيل الدخول
        'login_desc' => 'سجل دخولك للوصول إلى لوحتك',
        'job_number' => 'الرقم الوظيفي',
        'enter_job_number' => 'أدخل الرقم الوظيفي',
        'password' => 'كلمة المرور',
        'enter_password' => 'أدخل كلمة المرور',
        'login_error' => 'الرقم الوظيفي أو كلمة المرور غير صحيحة',
        'system_error' => 'حدث خطأ في النظام',
        'back_to_home' => 'العودة للرئيسية',
        'demo_accounts' => 'حسابات تجريبية',
        
        // صفحة إنشاء الحساب
        'register' => 'إنشاء حساب',
        'register_desc' => 'أنشئ حساباً جديداً للوصول إلى النظام',
        'confirm_password' => 'تأكيد كلمة المرور',
        'enter_full_name' => 'أدخل الاسم الكامل',
        'enter_email' => 'أدخل البريد الإلكتروني',
        'enter_phone' => 'أدخل رقم الهاتف',
        'enter_location' => 'أدخل الموقع',
        'select_role' => 'اختر الدور',
        'register_success' => 'تم إنشاء الحساب بنجاح! يمكنك تسجيل الدخول الآن',
        'register_error' => 'حدث خطأ أثناء إنشاء الحساب',
        'job_number_exists' => 'الرقم الوظيفي موجود بالفعل',
        'password_mismatch' => 'كلمات المرور غير متطابقة',
        'password_short' => 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        'invalid_email' => 'البريد الإلكتروني غير صحيح',
        'have_account' => 'لديك حساب بالفعل؟',
        'register_link' => 'إنشاء حساب جديد',
        
        // لوحة التحكم العامة
        'dashboard' => 'لوحة التحكم',
        'profile' => 'الملف الشخصي',
        'logout' => 'تسجيل الخروج',
        'welcome' => 'مرحباً',
        'total_users' => 'إجمالي المستخدمين',
        'total_tasks' => 'إجمالي المهام',
        'completed_tasks' => 'المهام المكتملة',
        'pending_tasks' => 'المهام المعلقة',
        'attendance' => 'الحضور',
        'tasks' => 'المهام',
        'reports' => 'التقارير',
        'settings' => 'الإعدادات',
        'search' => 'بحث...',
        'actions' => 'الإجراءات',
        'save' => 'حفظ',
        'cancel' => 'إلغاء',
        'edit' => 'تعديل',
        'delete' => 'حذف',
        'view' => 'عرض',
        'add_new' => 'إضافة جديد',
        'status' => 'الحالة',
        'date' => 'التاريخ',
        'time' => 'الوقت',
        'description' => 'الوصف',
        'location' => 'الموقع',
        'priority' => 'الأولوية',
        'high' => 'عالية',
        'medium' => 'متوسطة',
        'low' => 'منخفضة',
        'submit' => 'إرسال',
        'clear' => 'مسح',
        
        // لوحة المالك
        'users_management' => 'إدارة المستخدمين',
        'create_user' => 'إنشاء مستخدم',
        'user_name' => 'اسم المستخدم',
        'full_name' => 'الاسم الكامل',
        'email' => 'البريد الإلكتروني',
        'phone' => 'الهاتف',
        'role' => 'الدور',
        'created_at' => 'تاريخ الإنشاء',
        'active' => 'نشط',
        'inactive' => 'غير نشط',
        
        // لوحة المشرف
        'assign_task' => 'تعيين مهمة',
        'assigned_tasks' => 'المهام المعينة',
        'task_name' => 'اسم المهمة',
        'assigned_to' => 'مخصص لـ',
        'due_date' => 'تاريخ الاستحقاق',
        'task_status' => 'حالة المهمة',
        'pending' => 'معلقة',
        'in_progress' => 'قيد التنفيذ',
        'completed' => 'مكتملة',
        'approved' => 'معتمدة',
        'worker_location' => 'موقع العامل',
        'assign' => 'تعيين',
        
        // لوحة العامل
        'my_tasks' => 'مهامي',
        'start_task' => 'بدء المهمة',
        'complete_task' => 'إكمال المهمة',
        'check_in' => 'تسجيل حضور',
        'check_out' => 'تسجيل انصراف',
        'today_tasks' => 'مهام اليوم',
        'working_hours' => 'ساعات العمل',
        'task_details' => 'تفاصيل المهمة',
        'notes' => 'ملاحظات',
        'attach_photo' => 'إرفاق صورة',
        'send_to_supervisor' => 'إرسال للمشرف',
        'home' => 'الرئيسية',
        'cleaning_worker' => 'عامل نظافة',
        'attendance_absence' => 'الحضور والغياب',
        'attendance_registered' => 'تم تسجيل الحضور',
        'check_in_time' => 'وقت الدخول',
        'check_out_time' => 'وقت الخروج',
        'total_hours' => 'إجمالي',
        'hour' => 'ساعة',
        'hours' => 'ساعات',
        'work_info' => 'معلومات الدوام',
        'current_work_hours' => 'ساعات العمل الحالية',
        'work_duration' => 'مدة الدوام',
        'checkout' => 'تسجيل الخروج',
        'checked_out' => 'تم الخروج',
        'attendance_not_registered' => 'لم يتم تسجيل الحضور اليوم',
        'register_attendance_desc' => 'قم بتسجيل دخول الدوام',
        'check_in_confirm' => 'هل تريد تسجيل دخول الدوام الآن؟',
        'enter_work' => 'دخول الدوام',
        'attend' => 'دخول',
        'end_work' => 'خروج',
        'end_work_confirm' => 'هل تريد الخروج وإنهاء العمل اليوم؟',
        'total_tasks_count' => 'إجمالي المهام',
        'completed_count' => 'مكتملة',
        'pending_count' => 'معلقة',
        'monthly_hours_label' => 'ساعة (هذا الشهر)',
        'view_all' => 'عرض الكل',
        'accept' => 'قبول',
        'reject' => 'رفض',
        'accept_start_confirm' => 'هل تريد قبول وبدء هذه المهمة؟',
        'reject_task_confirm' => 'هل تريد رفض هذه المهمة؟',
        'task_rejected_success' => 'تم رفض المهمة بنجاح',
        'completion_notes_optional' => 'ملاحظات (اختياري)',
        'completion_notes_placeholder' => 'أضف ملاحظات حول إكمال المهمة...',
        'upload_images_optional' => 'رفع صور (اختياري - يمكن رفع أكثر من صورة)',
        'select_multiple_images' => 'يمكنك اختيار أكثر من صورة',
        'audio_recording_optional' => 'تسجيل صوتي (اختياري)',
        'start_recording' => 'بدء التسجيل',
        'stop_recording' => 'إيقاف التسجيل',
        'upload_audio_file' => 'أو قم برفع ملف صوتي',
        'complete_task_btn' => 'إكمال المهمة',
        'not_complete_task' => 'عدم إكمال المهمة',
        'not_completion_notes_placeholder' => 'أضف ملاحظات حول سبب عدم إكمال المهمة...',
        'register_not_completion' => 'تسجيل عدم الإكمال',
        
        // التقارير
        'daily_report' => 'تقرير يومي',
        'weekly_report' => 'تقرير أسبوعي',
        'monthly_report' => 'تقرير شهري',
        'performance_report' => 'تقرير الأداء',
        'generate_report' => 'إنشاء تقرير',
        'download' => 'تحميل',
        'print' => 'طباعة',
        
        // التنبيهات
        'success' => 'تمت العملية بنجاح',
        'error' => 'حدث خطأ',
        'warning' => 'تحذير',
        'info' => 'معلومة',
        'confirm_delete' => 'هل أنت متأكد من الحذف؟',
        'no_data' => 'لا توجد بيانات',
        'loading' => 'جاري التحميل...',
        'update' => 'تحديث',
        'user_created' => 'تم إنشاء المستخدم بنجاح',
        'user_updated' => 'تم تحديث المستخدم بنجاح',
        'user_deleted' => 'تم حذف المستخدم بنجاح',
        'task_created' => 'تم إنشاء المهمة بنجاح',
        'task_updated' => 'تم تحديث المهمة بنجاح',
        'task_deleted' => 'تم حذف المهمة بنجاح',
        'area' => 'المنطقة',
        'building' => 'المبنى',
        'floor' => 'الدور',
        'supervisor' => 'المشرف',
        'worker' => 'العامل',
        'all_users' => 'جميع المستخدمين',
        'all_tasks' => 'جميع المهام',
        'filter' => 'تصفية',
        'reset' => 'إعادة تعيين',
        
        // رسائل الحضور والانصراف
        'attendance_already_registered' => 'لديك حضور نشط اليوم. يرجى إنهاء الدوام الحالي أولاً',
        'attendance_registered_success' => 'تم تسجيل الحضور بنجاح',
        'attendance_not_registered_today' => 'لم يتم تسجيل الحضور اليوم',
        'checkout_already_registered' => 'تم تسجيل الانصراف بالفعل',
        'checkout_success' => 'تم تسجيل الانصراف بنجاح. إجمالي ساعات العمل',
        'checkout_confirm' => 'هل تريد تسجيل الانصراف الآن؟',
        'attendance_rejected_success' => 'تم رفض بدء الدوام بنجاح',
        'reject_work' => 'رفض بدء الدوام',
        'reject_work_confirm' => 'هل تريد رفض بدء الدوام اليوم؟',
        'work_status' => 'حالة الدوام',
        'in_work' => 'في الدوام',
        'not_in_work' => 'غير مداوم',
        'please_check_in' => 'يرجى تسجيل الدخول أولاً',
        
        // رسائل المهام
        'task_started_success' => 'تم بدء المهمة بنجاح',
        'task_not_found_or_cannot_start' => 'المهمة غير موجودة أو لا يمكن بدءها',
        'task_not_found_or_cannot_complete' => 'المهمة غير موجودة أو لا يمكن إكمالها',
        'task_not_found_or_cannot_update' => 'المهمة غير موجودة أو لا يمكن تحديثها',
        'task_completed_success' => 'تم إكمال المهمة بنجاح',
        'task_non_completion_registered' => 'تم تسجيل عدم إكمال المهمة بنجاح',
        'task_not_found_or_no_permission' => 'المهمة غير موجودة أو ليس لديك صلاحية للوصول إليها',
        'start_task_confirm' => 'هل تريد بدء هذه المهمة؟',
        'view_details' => 'عرض التفاصيل',
        'start_time' => 'وقت البدء',
        'completion_time' => 'وقت الإكمال',
        
        // رسائل عامة
        'close' => 'إغلاق',
        'microphone_access_error' => 'لا يمكن الوصول إلى الميكروفون. يرجى التحقق من الصلاحيات.',
        'role_worker' => 'عامل نظافة',
        'language' => 'اللغة',
        'arabic' => 'العربية',
        'english' => 'English',
        'close_btn' => 'إغلاق',
        'in_progress_count' => 'قيد التنفيذ',
        'translate_page' => 'ترجمة الصفحة'
    ];
} else {
    // English
    $lang = [
        'site_title' => 'Murafaaq',
        'welcome_title' => 'Welcome to Cleaning Management System',
        'welcome_desc' => 'Integrated system for managing and tracking cleaning operations in areas and buildings',
        'login' => 'Login',
        'learn_more' => 'Learn More',
        'features' => 'System Features',
        'role_admin' => 'Owner',
        'role_admin_desc' => 'General supervision, account creation, and report viewing',
        'role_supervisor' => 'Supervisor',
        'role_supervisor_desc' => 'Determining worker locations and assigning tasks',
        'role_worker' => 'Cleaning Worker',
        'role_worker_desc' => 'Receiving tasks and recording completion',
        'footer_desc' => 'Integrated Cleaning Management System',
        'all_rights' => 'All rights reserved',
        
        // Login page
        'login_desc' => 'Login to access your dashboard',
        'job_number' => 'Job Number',
        'enter_job_number' => 'Enter job number',
        'password' => 'Password',
        'enter_password' => 'Enter password',
        'login_error' => 'Incorrect job number or password',
        'system_error' => 'System error occurred',
        'back_to_home' => 'Back to Home',
        'demo_accounts' => 'Demo Accounts',
        
        // Register page
        'register' => 'Register',
        'register_desc' => 'Create a new account to access the system',
        'confirm_password' => 'Confirm Password',
        'enter_full_name' => 'Enter full name',
        'enter_email' => 'Enter email address',
        'enter_phone' => 'Enter phone number',
        'enter_location' => 'Enter location',
        'select_role' => 'Select role',
        'register_success' => 'Account created successfully! You can login now',
        'register_error' => 'An error occurred while creating the account',
        'job_number_exists' => 'Job number already exists',
        'password_mismatch' => 'Passwords do not match',
        'password_short' => 'Password must be at least 6 characters',
        'invalid_email' => 'Invalid email address',
        'have_account' => 'Already have an account?',
        'register_link' => 'Create new account',
        
        // General dashboard
        'dashboard' => 'Dashboard',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'welcome' => 'Welcome',
        'total_users' => 'Total Users',
        'total_tasks' => 'Total Tasks',
        'completed_tasks' => 'Completed Tasks',
        'pending_tasks' => 'Pending Tasks',
        'attendance' => 'Attendance',
        'tasks' => 'Tasks',
        'reports' => 'Reports',
        'settings' => 'Settings',
        'search' => 'Search...',
        'actions' => 'Actions',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'view' => 'View',
        'add_new' => 'Add New',
        'status' => 'Status',
        'date' => 'Date',
        'time' => 'Time',
        'description' => 'Description',
        'location' => 'Location',
        'priority' => 'Priority',
        'high' => 'High',
        'medium' => 'Medium',
        'low' => 'Low',
        'submit' => 'Submit',
        'clear' => 'Clear',
        
        // Owner dashboard
        'users_management' => 'Users Management',
        'create_user' => 'Create User',
        'user_name' => 'Username',
        'full_name' => 'Full Name',
        'email' => 'Email',
        'phone' => 'Phone',
        'role' => 'Role',
        'created_at' => 'Created At',
        'active' => 'Active',
        'inactive' => 'Inactive',
        
        // Supervisor dashboard
        'assign_task' => 'Assign Task',
        'assigned_tasks' => 'Assigned Tasks',
        'task_name' => 'Task Name',
        'assigned_to' => 'Assigned To',
        'due_date' => 'Due Date',
        'task_status' => 'Task Status',
        'pending' => 'Pending',
        'in_progress' => 'In Progress',
        'completed' => 'Completed',
        'approved' => 'Approved',
        'worker_location' => 'Worker Location',
        'assign' => 'Assign',
        
        // Worker dashboard
        'my_tasks' => 'My Tasks',
        'start_task' => 'Start Task',
        'complete_task' => 'Complete Task',
        'check_in' => 'Check In',
        'check_out' => 'Check Out',
        'today_tasks' => 'Today\'s Tasks',
        'working_hours' => 'Working Hours',
        'task_details' => 'Task Details',
        'notes' => 'Notes',
        'attach_photo' => 'Attach Photo',
        'send_to_supervisor' => 'Send to Supervisor',
        'home' => 'Home',
        'cleaning_worker' => 'Cleaning Worker',
        'attendance_absence' => 'Attendance & Absence',
        'attendance_registered' => 'Attendance Registered',
        'check_in_time' => 'Check In Time',
        'check_out_time' => 'Check Out Time',
        'total_hours' => 'Total',
        'hour' => 'hour',
        'hours' => 'hours',
        'work_info' => 'Work Information',
        'current_work_hours' => 'Current Work Hours',
        'work_duration' => 'Work Duration',
        'checkout' => 'Check Out',
        'checked_out' => 'Checked Out',
        'attendance_not_registered' => 'Attendance not registered today',
        'register_attendance_desc' => 'Register work attendance',
        'check_in_confirm' => 'Do you want to check in now?',
        'enter_work' => 'Enter Work',
        'attend' => 'Enter',
        'end_work' => 'Exit',
        'end_work_confirm' => 'Do you want to exit and finish work today?',
        'total_tasks_count' => 'Total Tasks',
        'completed_count' => 'Completed',
        'pending_count' => 'Pending',
        'monthly_hours_label' => 'hours (this month)',
        'view_all' => 'View All',
        'accept' => 'Accept',
        'reject' => 'Reject',
        'accept_start_confirm' => 'Do you want to accept and start this task?',
        'reject_task_confirm' => 'Do you want to reject this task?',
        'task_rejected_success' => 'Task rejected successfully',
        'completion_notes_optional' => 'Notes (optional)',
        'completion_notes_placeholder' => 'Add notes about task completion...',
        'upload_images_optional' => 'Upload Images (optional - can upload multiple)',
        'select_multiple_images' => 'You can select multiple images',
        'audio_recording_optional' => 'Audio Recording (optional)',
        'start_recording' => 'Start Recording',
        'stop_recording' => 'Stop Recording',
        'upload_audio_file' => 'Or upload an audio file',
        'complete_task_btn' => 'Complete Task',
        'not_complete_task' => 'Not Complete Task',
        'not_completion_notes_placeholder' => 'Add notes about why the task was not completed...',
        'register_not_completion' => 'Register Non-Completion',
        
        // Reports
        'daily_report' => 'Daily Report',
        'weekly_report' => 'Weekly Report',
        'monthly_report' => 'Monthly Report',
        'performance_report' => 'Performance Report',
        'generate_report' => 'Generate Report',
        'download' => 'Download',
        'print' => 'Print',
        
        // Alerts
        'success' => 'Operation completed successfully',
        'error' => 'An error occurred',
        'warning' => 'Warning',
        'info' => 'Information',
        'confirm_delete' => 'Are you sure you want to delete?',
        'no_data' => 'No data available',
        'loading' => 'Loading...',
        'update' => 'Update',
        'user_created' => 'User created successfully',
        'user_updated' => 'User updated successfully',
        'user_deleted' => 'User deleted successfully',
        'task_created' => 'Task created successfully',
        'task_updated' => 'Task updated successfully',
        'task_deleted' => 'Task deleted successfully',
        'area' => 'Area',
        'building' => 'Building',
        'floor' => 'Floor',
        'supervisor' => 'Supervisor',
        'worker' => 'Worker',
        'all_users' => 'All Users',
        'all_tasks' => 'All Tasks',
        'filter' => 'Filter',
        'reset' => 'Reset',
        
        // Attendance messages
        'attendance_already_registered' => 'You have an active attendance today. Please end your current work session first',
        'attendance_registered_success' => 'Attendance registered successfully',
        'attendance_not_registered_today' => 'Attendance not registered today',
        'checkout_already_registered' => 'Checkout already registered',
        'checkout_success' => 'Checkout registered successfully. Total working hours',
        'checkout_confirm' => 'Do you want to check out now?',
        'attendance_rejected_success' => 'Work start rejected successfully',
        'reject_work' => 'Reject Work Start',
        'reject_work_confirm' => 'Do you want to reject starting work today?',
        'work_status' => 'Work Status',
        'in_work' => 'In Work',
        'not_in_work' => 'Not in Work',
        'please_check_in' => 'Please check in first',
        
        // Task messages
        'task_started_success' => 'Task started successfully',
        'task_not_found_or_cannot_start' => 'Task not found or cannot be started',
        'task_not_found_or_cannot_complete' => 'Task not found or cannot be completed',
        'task_not_found_or_cannot_update' => 'Task not found or cannot be updated',
        'task_completed_success' => 'Task completed successfully',
        'task_non_completion_registered' => 'Task non-completion registered successfully',
        'task_not_found_or_no_permission' => 'Task not found or you do not have permission to access it',
        'start_task_confirm' => 'Do you want to start this task?',
        'view_details' => 'View Details',
        'start_time' => 'Start Time',
        'completion_time' => 'Completion Time',
        
        // General messages
        'close' => 'Close',
        'microphone_access_error' => 'Cannot access microphone. Please check permissions.',
        'role_worker' => 'Cleaning Worker',
        'language' => 'Language',
        'arabic' => 'Arabic',
        'english' => 'English',
        'close_btn' => 'Close',
        'in_progress_count' => 'In Progress',
        'translate_page' => 'Translate Page'
    ];
}

// معالجة تغيير اللغة
if (isset($_GET['lang'])) {
    $lang_code = $_GET['lang'];
    if (in_array($lang_code, ['ar', 'en'])) {
        $_SESSION['lang'] = $lang_code;
    }
}
?>

